version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: svelte
    versions:
    - 3.31.0
    - 3.32.1
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.5
  - dependency-name: lodash
    versions:
    - 4.17.20
